"""add birth_date column

Revision ID: 0f053932c30c
Revises: 5b3bf1016f9c
Create Date: 2026-03-13 12:52:15.338071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f053932c30c'
down_revision: Union[str, Sequence[str], None] = '5b3bf1016f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('birth_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_children_birth_date'), 'children', ['birth_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_children_birth_date'), table_name='children')
    op.drop_column('children', 'birth_date')
    # ### end Alembic commands ###
