"""initial_tables

Revision ID: 1f980c2333d9
Revises: 
Create Date: 2026-05-06 17:42:23.967223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f980c2333d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_child_id'), 'audit_logs', ['child_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_parent_id'), 'audit_logs', ['parent_id'], unique=False)
    op.create_table('parents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=True)
    op.create_index(op.f('ix_parents_firebase_uid'), 'parents', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_parents_name'), 'parents', ['name'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('focus_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_children_interests_gin', 'children', ['interests'], unique=False, postgresql_using='gin')
    op.create_index('idx_children_keywords_gin', 'children', ['keywords_filter'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_children_birth_date'), 'children', ['birth_date'], unique=False)
    op.create_index(op.f('ix_children_created_at'), 'children', ['created_at'], unique=False)
    op.create_index(op.f('ix_children_is_deleted'), 'children', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_children_parent_id'), 'children', ['parent_id'], unique=True)
    op.create_table('analytics_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('analytics_date', sa.Date(), nullable=False),
    sa.Column('fq', sa.Float(), nullable=True),
    sa.Column('vq', sa.Float(), nullable=True),
    sa.Column('cq', sa.Float(), nullable=True),
    sa.Column('mq', sa.Float(), nullable=True),
    sa.Column('gq', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'analytics_date', name='uq_child_daily_analytics')
    )
    op.create_index('idx_analytics_child_date', 'analytics_history', ['child_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_history_analytics_date'), 'analytics_history', ['analytics_date'], unique=False)
    op.create_index(op.f('ix_analytics_history_child_id'), 'analytics_history', ['child_id'], unique=False)
    op.create_index(op.f('ix_analytics_history_created_at'), 'analytics_history', ['created_at'], unique=False)
    op.create_table('child_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('fq', sa.Float(), nullable=False),
    sa.Column('vq', sa.Float(), nullable=False),
    sa.Column('cq', sa.Float(), nullable=False),
    sa.Column('mq', sa.Float(), nullable=False),
    sa.Column('gq', sa.Float(), nullable=False),
    sa.Column('velocity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trend_percent', sa.Float(), nullable=True),
    sa.Column('breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insight_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('algorithm_version', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_analytics_child_id'), 'child_analytics', ['child_id'], unique=True)
    op.create_index(op.f('ix_child_analytics_updated_at'), 'child_analytics', ['updated_at'], unique=False)
    op.create_table('child_vocabulary_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'word', name='uq_child_word_memory')
    )
    op.create_index('idx_child_vocab_child_word_lower', 'child_vocabulary_memory', ['child_id', sa.text('lower(word)')], unique=False)
    op.create_index('idx_vocab_child_first_seen', 'child_vocabulary_memory', ['child_id', 'first_seen'], unique=False)
    op.create_index(op.f('ix_child_vocabulary_memory_child_id'), 'child_vocabulary_memory', ['child_id'], unique=False)
    op.create_index(op.f('ix_child_vocabulary_memory_first_seen'), 'child_vocabulary_memory', ['first_seen'], unique=False)
    op.create_index(op.f('ix_child_vocabulary_memory_last_seen'), 'child_vocabulary_memory', ['last_seen'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('conversation_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'conversation_date', name='uq_child_daily_conversation')
    )
    op.create_index('idx_conversation_child_date', 'conversations', ['child_id', 'conversation_date'], unique=False)
    op.create_index(op.f('ix_conversations_child_id'), 'conversations', ['child_id'], unique=False)
    op.create_index(op.f('ix_conversations_conversation_date'), 'conversations', ['conversation_date'], unique=False)
    op.create_table('interaction_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('smart_adapt_mode', sa.Boolean(), nullable=True),
    sa.Column('custom_tune', sa.Boolean(), nullable=True),
    sa.Column('word_complexity', sa.Integer(), nullable=True),
    sa.Column('speech_speed', sa.Integer(), nullable=True),
    sa.Column('new_words_per_session', sa.Integer(), nullable=True),
    sa.Column('question_frequency', sa.String(), nullable=True),
    sa.Column('topic_focus', sa.Integer(), nullable=True),
    sa.Column('command_steps', sa.Integer(), nullable=True),
    sa.Column('patience_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_settings_child_id'), 'interaction_settings', ['child_id'], unique=True)
    op.create_index(op.f('ix_interaction_settings_created_at'), 'interaction_settings', ['created_at'], unique=False)
    op.create_table('toys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('toy_uuid', sa.UUID(), nullable=False),
    sa.Column('factory_device_id', sa.String(), nullable=False),
    sa.Column('owner_parent_id', sa.UUID(), nullable=True),
    sa.Column('active_child_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PROVISIONED', 'ACTIVE', 'DISABLED', name='toystatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manufactured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('factory_batch', sa.String(), nullable=True),
    sa.Column('hardware_revision', sa.String(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('wifi_signal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['owner_parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toys_active_child_id'), 'toys', ['active_child_id'], unique=False)
    op.create_index(op.f('ix_toys_created_at'), 'toys', ['created_at'], unique=False)
    op.create_index(op.f('ix_toys_factory_batch'), 'toys', ['factory_batch'], unique=False)
    op.create_index(op.f('ix_toys_factory_device_id'), 'toys', ['factory_device_id'], unique=True)
    op.create_index(op.f('ix_toys_owner_parent_id'), 'toys', ['owner_parent_id'], unique=False)
    op.create_index(op.f('ix_toys_toy_uuid'), 'toys', ['toy_uuid'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('toy_id', sa.UUID(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_key_hash_revoked', 'api_keys', ['key_hash', 'revoked'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_toy_id'), 'api_keys', ['toy_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_api_keys_toy_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index('idx_api_key_hash_revoked', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_toys_toy_uuid'), table_name='toys')
    op.drop_index(op.f('ix_toys_owner_parent_id'), table_name='toys')
    op.drop_index(op.f('ix_toys_factory_device_id'), table_name='toys')
    op.drop_index(op.f('ix_toys_factory_batch'), table_name='toys')
    op.drop_index(op.f('ix_toys_created_at'), table_name='toys')
    op.drop_index(op.f('ix_toys_active_child_id'), table_name='toys')
    op.drop_table('toys')
    op.drop_index(op.f('ix_interaction_settings_created_at'), table_name='interaction_settings')
    op.drop_index(op.f('ix_interaction_settings_child_id'), table_name='interaction_settings')
    op.drop_table('interaction_settings')
    op.drop_index(op.f('ix_conversations_conversation_date'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_child_id'), table_name='conversations')
    op.drop_index('idx_conversation_child_date', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_child_vocabulary_memory_last_seen'), table_name='child_vocabulary_memory')
    op.drop_index(op.f('ix_child_vocabulary_memory_first_seen'), table_name='child_vocabulary_memory')
    op.drop_index(op.f('ix_child_vocabulary_memory_child_id'), table_name='child_vocabulary_memory')
    op.drop_index('idx_vocab_child_first_seen', table_name='child_vocabulary_memory')
    op.drop_index('idx_child_vocab_child_word_lower', table_name='child_vocabulary_memory')
    op.drop_table('child_vocabulary_memory')
    op.drop_index(op.f('ix_child_analytics_updated_at'), table_name='child_analytics')
    op.drop_index(op.f('ix_child_analytics_child_id'), table_name='child_analytics')
    op.drop_table('child_analytics')
    op.drop_index(op.f('ix_analytics_history_created_at'), table_name='analytics_history')
    op.drop_index(op.f('ix_analytics_history_child_id'), table_name='analytics_history')
    op.drop_index(op.f('ix_analytics_history_analytics_date'), table_name='analytics_history')
    op.drop_index('idx_analytics_child_date', table_name='analytics_history')
    op.drop_table('analytics_history')
    op.drop_index(op.f('ix_children_parent_id'), table_name='children')
    op.drop_index(op.f('ix_children_is_deleted'), table_name='children')
    op.drop_index(op.f('ix_children_created_at'), table_name='children')
    op.drop_index(op.f('ix_children_birth_date'), table_name='children')
    op.drop_index('idx_children_keywords_gin', table_name='children', postgresql_using='gin')
    op.drop_index('idx_children_interests_gin', table_name='children', postgresql_using='gin')
    op.drop_table('children')
    op.drop_index(op.f('ix_parents_name'), table_name='parents')
    op.drop_index(op.f('ix_parents_firebase_uid'), table_name='parents')
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_audit_logs_parent_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_child_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
