"""add child vocabulary memory

Revision ID: 5b3bf1016f9c
Revises: 2827c0dea436
Create Date: 2026-03-12 13:00:02.699379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3bf1016f9c'
down_revision: Union[str, Sequence[str], None] = '2827c0dea436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_vocabulary_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'word', name='uq_child_word_memory')
    )
    op.create_index('idx_child_vocab_child_word', 'child_vocabulary_memory', ['child_id', 'word'], unique=False)
    op.create_index(op.f('ix_child_vocabulary_memory_child_id'), 'child_vocabulary_memory', ['child_id'], unique=False)
    op.create_index(op.f('ix_child_vocabulary_memory_first_seen'), 'child_vocabulary_memory', ['first_seen'], unique=False)
    op.create_index(op.f('ix_child_vocabulary_memory_last_seen'), 'child_vocabulary_memory', ['last_seen'], unique=False)
    op.create_index(op.f('ix_child_vocabulary_memory_word'), 'child_vocabulary_memory', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_child_vocabulary_memory_word'), table_name='child_vocabulary_memory')
    op.drop_index(op.f('ix_child_vocabulary_memory_last_seen'), table_name='child_vocabulary_memory')
    op.drop_index(op.f('ix_child_vocabulary_memory_first_seen'), table_name='child_vocabulary_memory')
    op.drop_index(op.f('ix_child_vocabulary_memory_child_id'), table_name='child_vocabulary_memory')
    op.drop_index('idx_child_vocab_child_word', table_name='child_vocabulary_memory')
    op.drop_table('child_vocabulary_memory')
    # ### end Alembic commands ###
