"""make_guardian_name_non_nullable

Revision ID: cc3b44bbc3d2
Revises: a3c9f1d72e44
Create Date: 2026-05-15 17:27:51.900371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3b44bbc3d2'
down_revision: Union[str, Sequence[str], None] = 'a3c9f1d72e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill NULLs before enforcing NOT NULL
    op.execute("UPDATE children SET guardian_name = '' WHERE guardian_name IS NULL")
    op.alter_column('children', 'guardian_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'guardian_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
